services:
  redis:
    image: redis:alpine
    ports:
      - "6381:6379"

  app:
    build: .
    container_name: app-1
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: celery_worker-1
    command: uv run celery -A app.utils.celery worker --loglevel=info
    shm_size: '2gb'
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=.
    depends_on:
      - redis

  flower:
    build: .
    container_name: flower-1
    command: uv run celery -A app.utils.celery flower --port=5555
    ports:
      - "5557:5555"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=.