[project]
name = "multi-source-scrapper-and-aggregrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "argon2-cffi>=25.1.0",
    "docker>=7.1.0",
    "fastapi>=0.135.3",
    "httpx>=0.28.1",
    "passlib[bcrypt]>=1.7.4",
    "pwdlib[bcrypt]>=0.3.0",
    "pydantic-settings>=2.13.1",
    "pydantic[email]>=2.13.0",
    "pyjwt>=2.12.1",
    "pymongo>=4.16.0",
    "python-multipart>=0.0.26",
    "redis>=7.4.0",
    "uvicorn>=0.44.0",
]
