[project]
name = "multi-source-scrapper-and-aggregrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "argon2-cffi>=25.1.0",
    "asgiref>=3.11.1",
    "beanie>=2.1.0",
    "beautifulsoup4>=4.14.3",
    "celery>=5.6.3",
    "docker>=7.1.0",
    "fastapi>=0.135.3",
    "flower>=2.0.1",
    "httpx>=0.28.1",
    "passlib[bcrypt]>=1.7.4",
    "pwdlib[bcrypt]>=0.3.0",
    "pydantic-settings>=2.13.1",
    "pydantic[email]>=2.13.0",
    "pyjwt>=2.12.1",
    "pymongo[srv]>=4.16.0",
    "pysonar>=1.4.0.4676",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.1.0",
    "python-multipart>=0.0.26",
    "redis>=7.4.0",
    "selenium>=4.43.0",
    "uvicorn>=0.44.0",
]


[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest-asyncio>=1.3.0",
]

[tool.pytest.ini_options]
# Correct way to set pythonpath in pyproject.toml
pythonpath = ["."]
testpaths = ["app/tests"]
asyncio_mode = "auto"
asyncio_default_test_loop_scope = "function"


[tool.coverage.run]
source = ["app"]
branch = true
